services:
  yourls:
    build:
      context: ./docker/yourls
    container_name: yourls_app
    env_file:
      - .env
    environment:
      YOURLS_SITE: ${YOURLS_SITE}
      YOURLS_USER: ${YOURLS_USER}
      YOURLS_PASS: ${YOURLS_PASS}
      YOURLS_DB_NAME: ${YOURLS_DB_NAME}
      YOURLS_DB_USER: ${YOURLS_DB_USER}
      YOURLS_DB_PASS: ${YOURLS_DB_PASS}
      YOURLS_DB_HOST: yourls_db
    ports:
      - "${YOURLS_HTTP_PORT:-9001}:9001"
    depends_on:
      yourls_db:
        condition: service_healthy
    volumes:
      - yourls_data:/var/www/html/user

  yourls_db:
    image: mysql:8.0
    container_name: yourls_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${YOURLS_DB_NAME}
      MYSQL_USER: ${YOURLS_DB_USER}
      MYSQL_PASSWORD: ${YOURLS_DB_PASS}
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - yourls_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  yourls_data:
  yourls_db_data:
